### ISSUE TITLE
Add application/x-bzip2 as a ZIP-based MIME type

### ISSUE THREAD

**Issue by coreydaley** [whatwg/mimesniff#106]
Would like to add application/x-bzip2 as a ZIP-based MIME type here: https://mimesniff.spec.whatwg.org/#zip-based-mime-type

**Comment by GPHemsley** [comment]
I think you are actually asking for bzip2 to be added to the list of archive type patterns:
https://mimesniff.spec.whatwg.org/#matching-an-archive-type-pattern

bzip2 is not a ZIP-based MIME type.

**Comment by coreydaley** [comment]
@GPHemsley It is also not an archive, maybe we need another classification for things such as gzip and bzip?

**Comment by GPHemsley** [comment]
I think perhaps the term "archive MIME type" is simply named wrong.

**Comment by coreydaley** [comment]
zip happens to do archiving and compression, whereas tar does archiving, and gzip/bzip do compression
