### ISSUE TITLE
re-classify application/x-gzip as a ZIP-based MIME type

### ISSUE THREAD

**Issue by coreydaley** [whatwg/mimesniff#107]
gzip does not, as far as I am aware, create an archive of multiple files and folders as does tar, zip, etc.  It uses a compression algorithm to shrink the file size, as such, it should be re-classified under the ZIP-based MIME type.

**Comment by GPHemsley** [comment]
A ZIP-based MIME type is one that is based off of the ZIP file format; that means things like JAR, XML-based Microsoft Office files, XPI, etc.

I think perhaps you are objecting to GZip being called an archive type?

**Comment by coreydaley** [comment]
@GPHemsley yes,
