### ISSUE TITLE
Algoritm for "Signature for MP3 without ID3 (6.2.3)" does not seem to be working.

### ISSUE THREAD

**Issue by finole12** [whatwg/mimesniff#11]
I am trying to implement the algoritm for determining an MP3 without ID3 in C#.
[https://mimesniff.spec.whatwg.org/#signature-for-mp3-without-id3](https://mimesniff.spec.whatwg.org/#signature-for-mp3-without-id3)

Some of the steps in the algoritm described seems to be wrong or are missing, here is what
I have found:

Under [To match an mp3 header](https://mimesniff.spec.whatwg.org/#match-an-mp3-header):
**_"4. If layer >> is not 0, return false."_**

There seems to be a number missing after the bitshift operator. The bitshift operator takes two arguments in the form of "x >> n".

Under [To compute an MP3 frame size](https://mimesniff.spec.whatwg.org/#compute-an-mp3-frame-size):
**_"2. Let size be bitrate \* scale / freq."_**

What is _freq_? Nowhere in the document are the variable _freq_ mentioned other than this line.

And last, the _"sample-rate table"_ looks like this: 

**_index    samplerate
0   44100
1   48000
T2  32000_**

What does the index _T2_ mean? should not all the indexes be numbers?

**Comment by annevk** [comment]
@padenot seems like you should take a look at this.

**Comment by padenot** [comment]
Up for review, thanks.

@finole12, a compatible implementation is available in the [Firefox sources], this is what I used to write this algorithm, but I made a number of mistakes when writing it down.

[Firefox sources]: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/mediasniffer/mp3sniff.c?from=mp3_sniff#118

**Comment by finole12** [comment]
Thanks, I'll have a look at the Firefox implementation and see if I can use it, but my C is a little rusty, so hopefully you can update the algorithm with a (working and tested) new version. Thanks for your work.

BTW my understanding fom the C implementation is you only need to read/buffer the first 1441 bytes from the file, is that correct?

**Comment by padenot** [comment]
@finole12, I've updated the algorithm, you can have a look at the new text here: <https://github.com/whatwg/mimesniff/issues/12> (preview: <https://rawgit.com/padenot/mimesniff/620ffd45bd6461587d40d8a72c9cc1ed0fd5cb7d/Overview.html#signature-for-mp3-without-id3>). It would be great if you could double check that it corresponds to the C code (we know that the C code works well).

Also, you need to read a maximum of 1445 bytes to determine if a file is an mp3 file, the maximum offset is 1441, but you need to read four bytes at this offset so you end up reading 1445 bytes in total.

**Comment by finole12** [comment]
@padenot I'm afraid my knowledge in C too limited to correctly review the algorithm against the C implementation, but I'll try the new version and see if it works. It might be some time though, as I have some other pressing issues. Thanks for replying.
