### ISSUE TITLE
Add application/x-xz as an archive MIME type 

### ISSUE THREAD

**Issue by LorbusChris** [whatwg/mimesniff#116]
I would like for `application/x-xz` to be added to the list of known MIME types

**Comment by annevk** [comment]
Could you share your motivation?

**Comment by LorbusChris** [comment]
Absolutely :)
The Golang-native `http.DetectContentType` function uses this library to detect MIME types,
and defaults to `application/octet-stream` for everything not included here.

Therefore we now need to vendor in another dependency into https://github.com/openshift/installer/pull/3160 to properly support `application/x-xz`, which is suboptimal.

**Comment by LorbusChris** [comment]
The use-case for that is downloading [Fedora CoreOS](https://getfedora.org/en/coreos/download/) images which are `xz` encoded

**Comment by annevk** [comment]
This is not a library, but rather a standard for when user agents are to perform sniffing in the context of the web and for safety reasons it's best not extended.

Unfortunately Golang seems to direct people for feature requests of that functionality here, but this really isn't the place for that.

**Comment by LorbusChris** [comment]
Unfortunately Golang devs point here for their list of supported MIME types (which doesn't make much sense, as this is clearly a browser focused spec). Feel free to close :)

**Comment by annevk** [comment]
Well, it's also focused on servers. If browsers and servers sniff differently that could lead to issues (and has in the past), but that also really depends on the context and what is being sniffed.

**Comment by LorbusChris** [comment]
That makes me wonder, what would be possible security implications when sniffing out e.g. the xz type?

**Comment by annevk** [comment]
I think one angle is user-supplied files, e.g., if the server thinks it's X and the browser Y, there might be an issue.
