### ISSUE TITLE
Should we still sniff if Content-Type is text/html?

### ISSUE THREAD

**Issue by cdumez** [whatwg/mimesniff#173]
I recently investigated a web-platform-test failure (html/semantics/embedded-content/the-iframe-element/iframe_sandbox_anchor_download_block_downloads.tentative.html) in WebKit/CFNetwork and found out that it was caused by sniffing when the Content-Type is text/html:
- https://github.com/web-platform-tests/wpt/pull/41037

This test is passing in Chrome and Firefox so I am wondering. Does the specification (https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource) really match Chrome and Firefox here?

Should CFNetwork stop sniffing when the Content-Type is text/html?

**Comment by cdumez** [comment]
cc @annevk

**Comment by annevk** [comment]
As far as I can tell from https://chromium.googlesource.com/chromium/src/net/+/refs/heads/main/base/mime_sniffer.cc Chromium does not appear to sniff `text/html` responses. They only invoke `SniffXML` (which is what they have for "feeds") for `text/xml` and `application/xml`. (Which seems to contradict step 4 of https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource which does not allow sniffing of XML MIME types.)

@MattMenke2 I see you touched that Chromium code quite a bit, any thoughts?

@valenting @mozfreddyb do either of you know what Gecko does for `text/html` responses? Do they get sniffed for feeds as the MIME Sniffing standard suggests in step 5 of https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource or are they not sniffed at all? (I got a bit lost trying to find the relevant callers of the functions in https://searchfox.org/mozilla-central/source/netwerk/streamconv/converters/nsUnknownDecoder.cpp.)

**Comment by josepharhar** [comment]
ccing some people who might be able to help with this
@ricea @horo-t @mikewest

**Comment by valenting** [comment]
> @valenting @mozfreddyb do either of you know what Gecko does for `text/html` responses? Do they get sniffed for feeds as the MIME Sniffing standard suggests in step 5 of https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource or are they not sniffed at all? (I got a bit lost trying to find the relevant callers of the functions in https://searchfox.org/mozilla-central/source/netwerk/streamconv/converters/nsUnknownDecoder.cpp.)

As far as I can tell we we don't create an nsUnknownDecoder if [it's already present on the response](https://searchfox.org/mozilla-central/rev/8f09f6a6ff0d8b6ea75a1e1279a06ba02479578c/netwerk/protocol/http/nsHttpChannel.cpp#1633,1643).
@farre and @sefeng211 have been working with this code recently so they might know more.

**Comment by mikewest** [comment]
cc @otherdaniel, who's looking into sniffing (or not) insofar as it impacts ORB.

**Comment by annevk** [comment]
@otherdaniel @valenting @farre @sefeng211 @MattMenke2 anyone willing to review #192?
