### ISSUE TITLE
Reflect RFC 8081 about font MIME type

### ISSUE THREAD

**Issue by LeoColomb** [whatwg/mimesniff#23]
[MIME types for fonts](https://mimesniff.spec.whatwg.org/commit-snapshots/ad24d0b6cd60962f8d007fde84ff609640e8e95b/#mime-type-groups) should reflect recent changes introduced by the [RFC 8081](https://tools.ietf.org/html/rfc8081) and [registered at IANA](https://www.iana.org/assignments/media-types/media-types.xml#font), isn't it?

Obsolete|Common
---|---
`application/font-ttf`|`font/ttf`
`application/font-cff`|`font/collection`
`application/font-off`|`font/otf`
`application/font-sfnt`|`font/sfnt`
`application/font-woff`|`font/woff`
| |`font/woff2`

**Comment by annevk** [comment]
I guess we could do that, though I'm not sure how this matters in practice.

**Comment by svgeesus** [comment]
RFC 8081 brings the IETF MIME specifications into alignment with actual deployed practice. Naturally, MIME Sniff should do the same.
Do you want a pull request?

**Comment by annevk** [comment]
The thing I don't quite understand is where these MIME types end up being exposed within a browser. As I understand it you can load fonts with `@font-face` and maybe there's an API these days too, but those end points ignore the MIME type and just let the font parser deal with the response body.

So at best this is an additional hint to the font parser, which it may or may not need.

(It doesn't seem like this algorithm is invoked from navigation, which would help determining how to download the resource (e.g., what file extension to pick).)

**Comment by annevk** [comment]
@GPHemsley do you recall why you added this font algorithm?

**Comment by GPHemsley** [comment]
Looking back on the history, the fonts section was originally added by Adam as a TODO. I think I just fleshed it out by doing research on the magic bytes of various font formats, and then continued developing it for parity with the other algorithms (along with the idea of `font` context used by e.g. `@font-face`).

Back then, RFC 8081 was just a glimmer in the eyes of a few devotees. As is still reflected in the current version of mimesniff, many fonts didn't even have standard/accepted MIME types at the time. It wasn't until WOFF and WOFF2 that things started to improve on that front.

**Comment by annevk** [comment]
Okay, in that case I support a PR @svgeesus. And we'll file a separate follow-up issue to make sure this code path actually ends up being used somewhere within the web platform in an observable way.
