### ISSUE TITLE
How to handle undocumented font mime type

### ISSUE THREAD

**Issue by bradleyfalzon** [whatwg/mimesniff#27]
Hi,

Apologies if this is the wrong place to ask, but https://mimesniff.spec.whatwg.org/#matching-a-font-type-pattern has 3 of the 5 fonts without a mime type.

For example, the first row specifies the font's mime type `application/vnd.ms-fontobject` given a particular byte and mask. But the 2nd through 4th rows don't appear to show a valid mime type.

In those cases, what mime type should be returned? I can guess TrueType and OpenType could both be `application/font-sfnt`, but I don't know about TrueType Collect. Or should we consider these undefined?

Thanks

**Comment by bradleyfalzon** [comment]
Any thoughts on this or is this not the appropriate forum?

**Comment by annevk** [comment]
We don't have an active maintainer for this repository, but it's definitely something that needs to be addressed.

**Comment by bradleyfalzon** [comment]
I understand I'll leave the issue open and just focus on the types that are defined.
