### ISSUE TITLE
Support for WOFF File Format 2.0

### ISSUE THREAD

**Issue by bradleyfalzon** [whatwg/mimesniff#28]
The font WOFF 2.0 is a W3C **Candidate** Recommendation for a font as defined https://www.w3.org/TR/WOFF2/

Although this is still a candidate recommendation (since 15th March 2016), is there any possibility to have this added to the mimesniff specification? It's widely supported, in most modern browsers: http://caniuse.com/#feat=woff2. Having support here, helps web servers sniff this type and set the correct content type headers.

The header is defined: https://www.w3.org/TR/WOFF2/#woff20Header as `77 4F 46 32` (the string "wOF2"), and the mime type `font/woff2` https://www.w3.org/TR/WOFF2/#IMT (also discussed in #23).

I'd be happy to PR this if you like.

**Comment by annevk** [comment]
Web servers? These sniffing rules are primarily aimed at browsers. Web servers ideally don't sniff but rather get told what the type of a resource is somehow.

**Comment by bradleyfalzon** [comment]
Sorry, I misspoke, specifically it's https://golang.org/pkg/net/http/#DetectContentType not specific to server or client.
