### ISSUE TITLE
MIME type parsing, duplicate parameters

### ISSUE THREAD

**Issue by annevk** [whatwg/mimesniff#41]
I thought I had already raised this, but `Content-Type: text/html;charset=gbk;charset=utf-8` results in UTF-8 in Chrome and Firefox, and GBK in Edge and Safari.

When there's duplicate headers there seems to be some preference to let the first header win; unclear what should apply here. My tendency would be to go with Edge and Safari as they have that kind of behavior and in practice it's easier to get Chrome and Firefox to align.

There's also a data model question here. Should MIME types support duplicate parameters (multimap of sorts) or is treating them as a normal map fine?

cc @bzbarsky @mcmanus @sleevi

**Comment by GPHemsley** [comment]
I agree with favoring the first one – I seem to recall that being specified somewhere. Maybe with `X-Content-Type-Options`?

**Comment by yutakahirano** [comment]
https://tools.ietf.org/html/rfc6838 says

> Parameter names are case-insensitive and no meaning is attached to
> the order in which they appear.  It is an error for a specific
> parameter to be specified more than once.

So *some* modules in Chrome (e.g., SendBeacon) handle it as not valid.

**Comment by annevk** [comment]
That RFC doesn't update or obsolete the definition of MIME types though. It's only about the registration procedure.

Is it important for SendBeacon for this to be an error? And if so, why is it not important elsewhere?

**Comment by yutakahirano** [comment]
> Is it important for SendBeacon for this to be an error? And if so, why is it not important elsewhere?

Probably not. I just wanted to tell the current status.

**Comment by annevk** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=788491 and https://bugzilla.mozilla.org/show_bug.cgi?id=1420575. This is also covered by tests linked from #42.
