### ISSUE TITLE
Sort out MIME type tests

### ISSUE THREAD

**Issue by annevk** [whatwg/mimesniff#42]
Tests:
* https://github.com/w3c/web-platform-tests/pull/7764 (navigation; charset handling, Blob/File/Request/Response)
* https://github.com/w3c/web-platform-tests/pull/8422 (XMLHttpRequest `Content-Type`)
* https://github.com/w3c/web-platform-tests/pull/8449 (XMLHttpRequest `overrideMimeType()`)
* https://github.com/w3c/web-platform-tests/pull/6890 (`data:` URLs)

Proposed processing model:
* https://github.com/whatwg/mimesniff/pull/36

TODO:

 - [x] Review #30 and #39 to come up with a more exhaustive set of endpoints and work out a testing story for those endpoints.
 - [x] Maybe file more implementation bugs.
 - [x] Close issues that were mostly raised as a tracker for tests and are covered by the above.
 - [x] Evaluate test results in all browsers as a means to: potentially change the processing model and tests and add more tests

**Comment by annevk** [comment]
Here's a start with an overview of the endpoints. Review and additions appreciated:



| Endpoint | Parsing | Serializing | "Supports" | "String" |
| --- | --- | --- | --- | --- |
| `media.canPlayType()`/`MediaSource.isTypeSupported()`/`MediaRecorder.isTypeSupported()` | ✅ | ❌ | ✅ | DOMString |
| XMLHttpRequest's `Content-Type`'s `charset` manipulation | ✅ | ✅ | ❌ | ByteString |
| XMLHttpRequest's `overrideMimeType()` | ✅ | ✅ | ❌ | DOMString |
| Navigation (hard to test) | ✅ | ❌ | ✅ | ByteString |
| `data:` URLs | ✅ | ❌/✅ | ❌/✅ | ByteString |
| `Blob`'s `type` | [?](https://github.com/w3c/FileAPI/issues/43) | ? | ❌ | ? |
| `Response` and `Request` | ✅ (not implemented) | ✅ (not implemented) | ❌ | ByteString |
| `DataTransfer` | [?](https://github.com/whatwg/html/issues/2947) | ? | ✅ | DOMString |

**Comment by annevk** [comment]
Thoughts:

* `canPlayType()` has adequate parsing tests. Those in charge of the `isTypeSupported()` methods should borrow from there.
* `XMLHttpRequest`'s `Content-Type`'s `charset` manipulation has some tests. It's worth noting that we only need to serialize the parsed value here if the given value can be successfully parsed and has a `charset` parameter.
* `XMLHttpRequest`'s `overrideMimeType()` could use more tests. The problem here is that the serialization depends on `Blob`'s `type` which is a mess (and doesn't always include parameters).
* Navigation: most of the encoding tests used to tease out parameter parsing are navigation tests of sorts.
* `data:` URLs: I created lots of tests for these.
* `Blob`'s `type`: it would really help to get some agreement on what to do here.
* `Response` and `Request`: depend on `Blob`'s type again...
* `DataTransfer`: fairly limited MIME type exposure.

My takeaway is that we need agreement on `Blob`'s `type` to make lots more progress, but we can make some progress around `XMLHttpRequest` `charset` manipulation.

**Comment by annevk** [comment]
https://github.com/w3c/web-platform-tests/pull/8422 has the XMLHttpRequest `Content-Type` tests and https://github.com/w3c/web-platform-tests/pull/6890 has them for `data:` URLs.

Until `Blob` is sorted that'll have to do, unless someone has further suggestions.

**Comment by annevk** [comment]
This is basically done, but leaving it open for now as it's a rather nice collection of data I might have to reference a few more times until all the patches have landed.

**Comment by snuggs** [comment]
WOW @annevk this is really great work. I have been perusing mimesniff as of late and definitely a space i'm interested in. I do realize you are keeping this open for "novelty"'s sake 😄. Is there anywhere here I can either help out? At minimum can contribute documentation.

I'll start understanding with the WPT tests in the description. I think I just answered my own question. 👍

**Comment by annevk** [comment]
The only bits I still need to finish are with respect to XMLHttpRequest. Implementations still have to align too unfortunately.

**Comment by snuggs** [comment]
@annevk been wondering this but didn't know how/where to ask. `preload` seems to send `*/*` for everything that's not style,font,etc.` since `as=document` is [broken ATM in chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=593267)
Wanted to know where do I bring up I think `as=document` should send the same mimetype as using the address bar (or a frame for that matter)? 

For example Chrome sends `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`.

I didn't know if this was a discussion for W3C/preload, mime sniff, HTML, WPT. Still getting the hang of wrangling kittens in open source (with your help of course).

Thanks in advance and I can delete comment after you respond if you like.

**Comment by annevk** [comment]
That's part of Fetch if you're talking about the `Accept` request header.

**Comment by snuggs** [comment]
@annevk copy. Thanks a ton!

**Comment by snuggs** [comment]
@annevk was going to submit an issue as didn't know where to ask questions. As you taught me, check existing issues/prs first before creating another. Even found the source in chrome. :-) Looks like there is a discussion going on to follow. Thanks again.

https://github.com/whatwg/fetch/issues/274

**Comment by annevk** [comment]
All the tests discussed here have landed.
