### ISSUE TITLE
MIME type parsing, stricter rules

### ISSUE THREAD

**Issue by annevk** [whatwg/mimesniff#44]
In https://chromium-review.googlesource.com/c/chromium/src/+/773321 @yutakahirano and @tyoshino work on a MIME type parser for XMLHttpRequest that is quite a bit stricter than the proposal in #36 (though not as strict as the RFC as far as I can tell; failing on `text/html;` would also undoubtedly break sites). If we can actually use that all over the web platform that is arguably somewhat better.

This is to track its success. I'd rather not block #36 on the outcome, but use the outcome to further refine the tests already written and the standard itself.

**Comment by annevk** [comment]
How would you pass those tests then though?

**Comment by domenic** [comment]
The tests are actually loosening the requirements by testing that the browser's output parses into the right value, instead of just testing the browser's output for an exact string match. In other words, they don't really test parsing, just serialization.

**Comment by annevk** [comment]
I see; I'd like us not to go in that direction. Maybe I should put up my own proposed modifications for that test for comparison.

**Comment by annevk** [comment]
Created https://github.com/w3c/web-platform-tests/pull/8422.

**Comment by annevk** [comment]
Closing this as a duplicate of #39 as that one is also focused on the XMLHttpRequest angle and there's not really anything new here apparently.
