### ISSUE TITLE
MIME type parsing, parameter canonicalization

### ISSUE THREAD

**Issue by domenic** [whatwg/mimesniff#46]
Apologies if this is a duplicate; I've kind of lost track.

https://github.com/w3c/web-platform-tests/pull/8422/files seems to imply there is no canonicalization of parameters performed. I would have imagined that the data model only contained strings, with quotes and slashes used to escape cases during serialization where necessary. Instead it appears that while slash-escapes are canonicalized, quotes are preserved.

If I am understanding correctly, this seems annoying, as then specs and implementations cannot do stuff like `if the parameter value is "UTF-8"` but instead have to do `if the parameter value is "UTF-8" or ""UTF-8""`.

**Comment by annevk** [comment]
This was #40. My plan is to have a special "get value" accessor (already defined in the PR). But maybe we should just do what you propose and see if it's compatible. There's not that many double quoted parameter values anyway.

@yutakahirano?

**Comment by annevk** [comment]
#36 now includes this in the draft.

**Comment by yutakahirano** [comment]
I would like to have 'UTF-8' and '"UTF-8"' identically. I think it's ok that parsing and serializing 'text/plain;charset="x"' results in 'text/plain;charset=x'.

**Comment by annevk** [comment]
Great, that's what the proposal does now. Still need to work on test coverage.

**Comment by annevk** [comment]
All PRs in #42 cover this now, including the less obvious cases.
