### ISSUE TITLE
Detect XML SOAP Envelop without Prolog

### ISSUE THREAD

**Issue by jccatrinck** [whatwg/mimesniff#71]
Hello i'm wondering if a XML SOAP Envelop can be considered a XML without the Prolog part.

_Maybe it can be a content-type:_  `application/soap+xml`

The tested SOAP Envelope was: `<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><env:Header><bpeCabecMsg xmlns="http://www.portalfiscal.inf.br/bpe"><cUF xmlns="http://www.portalfiscal.inf.br/bpe">41</cUF><versaoDados xmlns="http://www.portalfiscal.inf.br/bpe">1.00</versaoDados></bpeCabecMsg></env:Header><env:Body xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><bpeStatusServicoBPResult xmlns="http://www.portalfiscal.inf.br/bpe/wsdl/BPeStatusServico"><retConsStatSe`

**Expected**: `text/xml` or `application/xml` or  `application/soap+xml`

**Given result**: `text/plain; charset=utf-8`

Prolog meaning: https://www.w3schools.com/xml/xml_syntax.asp

**Comment by annevk** [comment]
We rather not extend the sniffing rules and instead have folks label things with the correct MIME type. Sniffing is pretty bad for security.
