### ISSUE TITLE
Adding '\n' support after html tags - specifically comment '<!--'

### ISSUE THREAD

**Issue by turbodonkey** [whatwg/mimesniff#8]
Hi I raised this issue on golang but they suggested we fix this upstream here, whats your thoughts around support for still detecting 'text/html' when the leading tag is '<!--' but the next char is not a ' ', its a whitespace char (inclusive of '\n' and '\t' ?)

I have a lot of html files that are incorrectly detected as 'text/plain' because i have an immediate '\n' after the opening '<!--' tag. Golang team basically saying, they'll merge if you fix.

Thoughts?

**Comment by annevk** [comment]
Why can't you just label your files with the correct MIME type?

**Comment by SamB** [comment]
Hmm, yeah, if have a problem with the way the code found in <https://golang.org/src/net/http/sniff.go> treats **your** files, then I think you are either (**a**) failing to set the correct `Content-Type` header at the server end or (**b**) using the algorithm for something for which it is not appropriate, like working around the fact that you forgot to come up with a way to keep track of the formats of your files (such as the ever-popular filename extension).

Of course, if they're not actually **your** files you *might* have a point.

**Comment by annevk** [comment]
Closing due to lack of follow-up.
